// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | ArticlesListSlice
  | ListSlice
  | NewHeroSlice;

/**
 * Item in *Homepage → menubar*
 */
export interface HomepageDocumentDataMenubarItem {
  /**
   * name field in *Homepage → menubar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.menubar[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * description field in *Homepage → menubar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.menubar[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * href field in *Homepage → menubar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.menubar[].href
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  href: prismic.RichTextField;

  /**
   * icon field in *Homepage → menubar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.menubar[].icon
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  icon: prismic.RichTextField;
}

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField /**
   * menubar field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.menubar[]
   * - **Tab**: nav
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  menubar: prismic.GroupField<Simplify<HomepageDocumentDataMenubarItem>>;

  /**
   * logo field in *Homepage*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.logo
   * - **Tab**: nav
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logo: prismic.LinkToMediaField;

  /**
   * loginbutton field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.loginbutton
   * - **Tab**: nav
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  loginbutton: prismic.LinkField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Primary content in *ArticlesList → Primary*
 */
export interface ArticlesListSliceDefaultPrimary {
  /**
   * title field in *ArticlesList → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_list.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *ArticlesList → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_list.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ArticlesList → Items*
 */
export interface ArticlesListSliceDefaultItem {
  /**
   * title field in *ArticlesList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_list.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *ArticlesList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_list.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * date field in *ArticlesList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_list.items[].date
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  date: prismic.RichTextField;

  /**
   * category field in *ArticlesList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_list.items[].category
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  category: prismic.RichTextField;

  /**
   * name field in *ArticlesList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_list.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * role field in *ArticlesList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_list.items[].role
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  role: prismic.RichTextField;

  /**
   * image field in *ArticlesList → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_list.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * datetime field in *ArticlesList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles_list.items[].datetime
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  datetime: prismic.RichTextField;
}

/**
 * Default variation for ArticlesList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticlesListSliceDefaultPrimary>,
  Simplify<ArticlesListSliceDefaultItem>
>;

/**
 * Slice variation for *ArticlesList*
 */
type ArticlesListSliceVariation = ArticlesListSliceDefault;

/**
 * ArticlesList Shared Slice
 *
 * - **API ID**: `articles_list`
 * - **Description**: ArticlesList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesListSlice = prismic.SharedSlice<
  "articles_list",
  ArticlesListSliceVariation
>;

/**
 * Primary content in *Collection → Primary*
 */
export interface ListSliceDefaultPrimary {
  /**
   * title field in *Collection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *Collection → Items*
 */
export interface ListSliceDefaultItem {
  /**
   * image field in *Collection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: list.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * name field in *Collection → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: list.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * description field in *Collection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Collection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ListSliceDefaultPrimary>,
  Simplify<ListSliceDefaultItem>
>;

/**
 * Slice variation for *Collection*
 */
type ListSliceVariation = ListSliceDefault;

/**
 * Collection Shared Slice
 *
 * - **API ID**: `list`
 * - **Description**: List
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSlice = prismic.SharedSlice<"list", ListSliceVariation>;

/**
 * Primary content in *NewHero → Primary*
 */
export interface NewHeroSliceDefaultPrimary {
  /**
   * title field in *NewHero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: new_hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *NewHero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: new_hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * button field in *NewHero → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: new_hero.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkToMediaField;
}

/**
 * Primary content in *NewHero → Items*
 */
export interface NewHeroSliceDefaultItem {
  /**
   * image field in *NewHero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: new_hero.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for NewHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewHeroSliceDefaultPrimary>,
  Simplify<NewHeroSliceDefaultItem>
>;

/**
 * Slice variation for *NewHero*
 */
type NewHeroSliceVariation = NewHeroSliceDefault;

/**
 * NewHero Shared Slice
 *
 * - **API ID**: `new_hero`
 * - **Description**: NewHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewHeroSlice = prismic.SharedSlice<
  "new_hero",
  NewHeroSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      HomepageDocumentDataMenubarItem,
      AllDocumentTypes,
      ArticlesListSlice,
      ArticlesListSliceDefaultPrimary,
      ArticlesListSliceDefaultItem,
      ArticlesListSliceVariation,
      ArticlesListSliceDefault,
      ListSlice,
      ListSliceDefaultPrimary,
      ListSliceDefaultItem,
      ListSliceVariation,
      ListSliceDefault,
      NewHeroSlice,
      NewHeroSliceDefaultPrimary,
      NewHeroSliceDefaultItem,
      NewHeroSliceVariation,
      NewHeroSliceDefault,
    };
  }
}
