import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { createClient } from '@/prismicio'
import Nav from '@/components/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const client = createClient();

  const nav = await client.getSingle("nav");
  
  return (
    <html lang="en">
      <body className={inter.className}>
          <Nav />
        {children}
        </body>
    </html>
  )
}
