// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  articles_list: dynamic(() => import("./ArticlesList")),
  list: dynamic(() => import("./Collection")),
  new_hero: dynamic(() => import("./NewHero")),
};
